# Store Models Parameters
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] 
BATCH_SIZE: 32
INCLUDE_TOP: False
EPOCHS: 5
CLASSES: 5
ACCEPTABLE_CLASSES: ['ALBATROSS', 'ANTBIRD', 'BOBOLINK', 'COCKATOO', 'CROW']
WEIGHTS: imagenet
LEARNING_RATE: 0.001
POOLING: 'max'